
CREATE TABLE  IF NOT EXISTS app_config(
  name varchar(64) NOT NULL ,
  value varchar(64) NOT NULL ,
  PRIMARY KEY (name)
);


CREATE TABLE  IF NOT EXISTS category(
  id INTEGER  NOT NULL,
  name varchar(200) NOT NULL ,
  PRIMARY KEY (id)
);
insert into category(id,name) values(1,'团队');
insert into category(id,name) values(2,'SMSC');
insert into category(id,name) values(3,'RCS');
insert into category(id,name) values(4,'MMSC');
insert into category(id,name) values(5,'SPAM');


CREATE TABLE  IF NOT EXISTS  todo_list (
  id INTEGER  GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  category_id int NOT NULL,
  category_name varchar(200)  NULL,
  title varchar(200) NOT NULL,
  content varchar(1024) NOT NULL,
  director varchar(50) NOT NULL,
  deadline datetime  NULL,
  quadrant int NOT NULL,
  remark varchar(1024)  NULL,
  PRIMARY KEY (id)
);

insert into todo_list(category_id,category_name,title,content,director,deadline,quadrant,remark) values(5,'SPAM','test','123123','丁吕涛','2021-01-12 12:12:12',1,'备注');
insert into todo_list(category_id,category_name,title,content,director,deadline,quadrant,remark) values(1,'团队','ddd','123144423','兰恩龙','2021-01-12 12:12:12',1,'备注333');